### ISSUE TITLE
data import

### ISSUE THREAD

**Issue by sibow** [City-of-Bloomington/incidents#1]
since I made some changes in the database, I need to import data from time to time and also to be able to import when going into production

**Comment by inghamn** [comment]
This would ideally be an SQL script that we could run to convert the old database schema into the new one.  After reviewing the ImportController, I believe this should be easy, but would require a little time to write out.

The ImportController is only doing SQL commands without java logic.

It would be useful to have an SQL script that we could use like this:
```bash
mysql -p incidents < old_incidents.sql
mysql -p incidents < migrate_db.sql
```

**Comment by sibow** [comment]
we went live and the import was successful
