### ISSUE TITLE
styles changes suggestions

### ISSUE THREAD

**Issue by sibow** [City-of-Bloomington/incidents#20]
label font is coming as regular, preferred bold
staff top menu now is in button list, preferred horizontal tabs
radio and checkbox text is showing underneath the checkbox preferred next to checkbox to the right, can be seen on the property page for theft incidents types.

**Comment by sibow** [comment]
I also notice that the tables that are still used in the staff part have no padding or spacing and this caused the text in the columns to be cramped together and hard to distinguish. I will try to replace some of the small tables, but we may still have some.

**Comment by adabutch** [comment]
- [x] **Label font is coming as regular, preferred bold.**

> <img width="549" alt="Screen Shot 2020-08-25 at 5 14 37 PM" src="https://user-images.githubusercontent.com/2372040/91238202-7cefc900-e70a-11ea-850c-4f224093a228.png">


- [x]  **Staff top menu is a button group, preferred horizontal tabs look.**
> <img width="690" alt="Screen Shot 2020-08-25 at 7 32 28 PM" src="https://user-images.githubusercontent.com/2372040/91238210-8711c780-e70a-11ea-977e-a7b6fa32a8a2.png">

- [x] **Staff tables padding + spacing.**
> <img width="623" alt="Screen Shot 2020-08-25 at 7 35 52 PM" src="https://user-images.githubusercontent.com/2372040/91238221-8b3de500-e70a-11ea-988e-b94a1de0300d.png">

**Comment by sibow** [comment]
- [x]  **Radio + Checkbox text is showing underneath the checkbox, preferred next to checkbox to the right (seen on the property page for theft incidents types).**

![property_radio](https://user-images.githubusercontent.com/1151576/91311166-c4b13780-e780-11ea-9a80-896570da22a1.png)

**Comment by sibow** [comment]
completed, thanks
