### ISSUE TITLE
Incorrect search results message

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/incidents#27]
When doing an incident search that returns results, the message at the top displays both the "No Results Found" and the "Found XX Results" messages.

**Comment by adabutch** [comment]
Also ~

After searching, then going back to the Search tab ... result counts are still persisting in the alert in addition to the message Cliff mentioned above.

<img width="787" alt="Screen Shot 2021-02-16 at 7 57 22 PM" src="https://user-images.githubusercontent.com/2372040/108141262-5eeb9b80-7091-11eb-9e56-2241330469c2.png">

cc // @sibow

**Comment by sibow** [comment]
fixed
